// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Venda.Infrastructure.Data;

#nullable disable

namespace Venda.Infrastructure.Migrations
{
    [DbContext(typeof(VendaDbContext))]
    [Migration("20251030220412_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.10");

            modelBuilder.Entity("Venda.Domain.Aggregates.VendaAgregado", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ClienteId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Data")
                        .HasColumnType("TEXT");

                    b.Property<string>("Filial")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("NumeroVenda")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId")
                        .HasDatabaseName("IX_Vendas_ClienteId");

                    b.HasIndex("Data")
                        .HasDatabaseName("IX_Vendas_Data");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_Vendas_Status");

                    b.HasIndex("ClienteId", "Data")
                        .HasDatabaseName("IX_Vendas_ClienteId_Data");

                    b.ToTable("Vendas", (string)null);
                });

            modelBuilder.Entity("Venda.Domain.Aggregates.VendaAgregado", b =>
                {
                    b.OwnsMany("Venda.Domain.ValueObjects.ItemVenda", "Produtos", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("INTEGER");

                            b1.Property<decimal>("Desconto")
                                .HasPrecision(5, 2)
                                .HasColumnType("TEXT")
                                .HasColumnName("Desconto");

                            b1.Property<Guid>("ProdutoId")
                                .HasColumnType("TEXT")
                                .HasColumnName("ProdutoId");

                            b1.Property<int>("Quantidade")
                                .HasColumnType("INTEGER")
                                .HasColumnName("Quantidade");

                            b1.Property<decimal>("ValorUnitario")
                                .HasPrecision(18, 2)
                                .HasColumnType("TEXT")
                                .HasColumnName("ValorUnitario");

                            b1.Property<Guid>("VendaId")
                                .HasColumnType("TEXT");

                            b1.HasKey("Id");

                            b1.HasIndex("VendaId");

                            b1.ToTable("ItensVenda", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("VendaId");
                        });

                    b.Navigation("Produtos");
                });
#pragma warning restore 612, 618
        }
    }
}
